#!/usr/bin/env bash

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# oh-my-zsh theme
ln -s $DOTFILES/themes/oh-my-zsh/twokul.zsh-theme $DOTFILES/oh-my-zsh/themes/twokul.zsh-theme

# zshrc config
ln -s $DOTFILES/shell/.config ~/.zshrc

# fzf autocompletions
$(brew --prefix)/opt/fzf/install

# Fish-like fast/unobtrusive autosuggestions for zsh.
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH/plugins/zsh-autosuggestions

# Additional completion definitions for Zsh
git clone https://github.com/zsh-users/zsh-completions $ZSH/plugins/zsh-completions

# Implementation of the Fish shell's history search feature
git clone https://github.com/zsh-users/zsh-history-substring-search $ZSH/plugins/zsh-history-substring-search

#
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/plugins/zsh-syntax-highlighting
