#!/usr/bin/env bash

# Install Plug https://github.com/junegunn/vim-plug

# Install for Vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Link Vim config files
ln -s $HOME/.dotfiles/vim/.vimrc $HOME/.vimrc

vim +PlugInstall
