#!/usr/bin/env fish

# Download oh-my-fish installer script but don't run it just yet
curl -L http://get.oh-my.fish | fish

ln -s ~/.dotfiles/oh-my-fish/bundle ~/.config/omf/bundle
ln -s ~/.dotfiles/oh-my-fish/channel ~/.config/omf/channel
ln -s ~/.dotfiles/oh-my-fish/theme ~/.config/omf/theme

omf install simple-ass-prompt
omf reload
