#!/usr/bin/env bash

https://github.com/joshdick/onedark.vim $HOME/.dotfiles/themes/onedark
# git clone https://github.com/sonph/onehalf.git $HOME/.dotfiles/themes/onehalf
# git clone https://github.com/benniemosher/the-one-theme/ $HOME/.dotfiles/themes/the-one-theme
