alias reload! "source ~/.config/fish/config.fish"

alias tns "tmux new -s"
alias ta "tmux attach -t"
alias tls "tmux ls"
alias tk "tmux kill-session -t"

alias nom "rm -rf node_modules; and npm cache clean; and npm i"
alias bom "rm -rf bower_components; and bower cache clean; and bower i"
alias ls "gls -F --color"
alias l "gls -lAh --color"
alias gl "git pull --prune"
alias glog "git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gca "git commit -a"
alias gco "git checkout"
alias gb "git branch"
alias grm "git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias gra "git remote add"
alias gum "git pull upstream master"
alias gr "git remote"
alias ga "git add"
alias gpf "git push origin HEAD --force"
alias gd "git diff"
alias gc "git commit -v"
alias gco "git checkout"
alias gs "git status -sb"
alias gp "git push origin HEAD"
alias gt "git tag"
alias gm "git merge"
alias gdt "git difftool"

alias puzzleslabs "ssh root@45.55.228.134"
alias twokul "ssh root@104.131.141.145"
alias git "hub"
