#!/usr/bin/env bash

# Add Fish to /etc/shells
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells

# Set Fish shell as the default shell
chsh -s `which fish`

# ln -s ~/.dotfiles/fish/config.fish ~/.config/fish/config.fish
