#!/usr/bin/env bash

# Setup default file paths and variables

# Make sure to make scripts under `bin/` available
export PATH=$HOME/.dotfiles/bin:$HOME/.cargo/bin:$PATH

# Code folder that we can `c [tab]` to
export PROJECTS=~/code

# Default editor
export EDITOR="vim"

export TERM=xterm-256color

source "$HOME/.dotfiles/env/aliases"

# _fzf
export FZF_COMPLETION_OPTS='+c -x'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# 'thefuck' command correction
eval "$(thefuck --alias)"

# Fix Alt + arrow keys, make them work as expected
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word
