#!/usr/bin/env bash

# Setup default file paths and variables

# Make sure to make scripts under `bin/` available
export PATH=$HOME/.dotfiles/bin:$HOME/.cargo/bin:$PATH

# Code folder that we can `c [tab]` to
export PROJECTS=~/code

# Default editor
export EDITOR="vim"

export TERM=xterm-256color

source "$HOME/.dotfiles/env/aliases"

# _fzf
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'
export FZF_COMPLETION_OPTS='+c -x'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,bower_components,.vscode,tmp}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"

# 'thefuck' command correction
eval "$(thefuck --alias)"

# Fix Alt + arrow keys, make them work as expected
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word

command -v tree > /dev/null && export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
